### PR TITLE
feat: New people added

### PR DESCRIPTION
**Pull request by navascogt**

### CODE REVIEW

**Comment by fcoterroba** [comment]
Hey! Thanks for contrib but please, add at least 5 persons famous in Spain or worldwide

**Comment by amosistech** [comment]
For sure, I will be adding more famous person later today... Thanks for the opportunity.

**Comment by amosistech** [comment]
Hi @fcoterroba , Added another commit with more people!

**Comment by navascogt** [comment]
Sorry for the confusion, navascogt and amosistech are my users, but the one used for Hacktoberfest is navascogt.

**Comment by fcoterroba** [comment]
Thanks for contribution!

**Comment by navascogt** [comment]
Hi @fcoterroba, just to be sure because I am new to this kind of collaboration, who is responsible of the action to delete the branch... The option is available to me, I must be responsible to do that? Thanks in advance for your advice.

**Pull request merged**
